version: "3"

services: 
    front:
        build: ./mande
        ports:
            - "3000:3000"
        environment: 
            CI: "true"
        depends_on: 
            - back
    back:
        build: ./backend
        ports:
            - "5000:5000"
        depends_on:
            - database
    database:
        image: mdillon/postgis
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_DB: "Mande"
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "pg123"
        volumes:
            - ./database:/docker-entrypoint-initdb.d
